export global Palette {
    out property <color> dark: #141414;
    out property <color> background_color: #2a2b31;
    out property <color> button_idle_color: #2a2b31;
    out property <color> button_hover_color: #6b3d3d;
    out property <color> button_pressed_color: #851a1a;

    out property <color> damage_button_idle_color: #661b1b;
    out property <color> damage_button_pressed_color: #831010;

    out property <color> heal_button_idle_color: #617c52;
    out property <color> heal_button_hover_color: #849c76;
    out property <color> heal_button_pressed_color: #4f6b3f;

    out property <color> temphp_button_idle_color: #395864;
    out property <color> temphp_button_hover_color: #506e7a;
    out property <color> temphp_button_pressed_color: #32728b;

    out property <color> normal_button_idle_color: #58575a;
    out property <color> normal_button_hover_color: #ad7e7e;
    out property <color> normal_button_pressed_color: #832323;

    out property <color> main_color: #969696;
    out property <color> text_color: #b3b3b6;

    out property <color> copper_color: #b87333;
    out property <color> silver_color: #C0C0C0;
    out property <color> electrum_color: #8FA8B3;
    out property <color> gold_color: #FFD700;
    out property <color> platinum_color: #E5E4E2;
 
    out property <color> current_hp_color: #DE7879;
    out property <color> temp_hp_color: #A8DDF0;

    out property <color> strength_color: #c1604d;
    out property <color> dexterity_color: #54DEB2;
    out property <color> constitution_color: #ECCF49;
    out property <color> intelligence_color: #8CC47B;
    out property <color> wisdom_color: #AB629C;
    out property <color> charisma_color: #E9DBCC;
}