import { Heading, Label, SavingThrow, Skill} from "../text_widgets.slint";
import { VerticalBox } from "std-widgets.slint";
import { Palette } from "../palette.slint";
import { Line } from "../drawing.slint";
import { SlintCharacter } from "../../logic.slint";

export component SavesProficiencies {
    in-out property <SlintCharacter> in-character;
    property <length> grid-width: 275px;

    callback set-skill-proficiency(string, bool);
    callback set-skill-expertise(string, bool);
    callback set-save-proficiency(string, bool);

    VerticalLayout {
        Heading {
            height: 40px;
            width: grid-width;
            text: "Saving Throws";
            color: Palette.text_color;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
        for save[i] in in-character.stats : SavingThrow {
            name: save.name;
            modifier: save.modifier_with_proficiency;
            color: save.color;
            proficient: save.saving-throw-proficiency;
            set-save-proficiency(name, val) => {
                set-save-proficiency(name, val);
            }
        }

        Heading {
            height: 40px;
            width: grid-width;
            text: "Proficiencies";
            color: Palette.text_color;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        for skill[i] in in-character.skills : Skill {
            name: skill.name;
            modifier: skill.modifier;
            color: skill.color;
            stat-short-name: "(" + skill.stat-short-name + ")";
            proficient: skill.proficiency; 
            expertise: skill.expertise;
            set-skill-proficiency(name, val) => {
                set-skill-proficiency(name, val);
            }
            set-skill-expertise(name, val) => {
                set-skill-expertise(name, val);
            }
        }

        Line {
            height: 12px;
            from: {x: 0, y: 0};
            to: {x: grid-width/1px, y: 0};
        }

        HorizontalLayout {
            Rectangle {
                width: grid-width * 0.03;
                height: 0px;
                border-radius: 0px;
            }
            Text {
                width: grid-width * 0.93;
                height: 200px;
                text: "Proficiencies & Languages\nLanguages: Common, Elven, Sylvan, Gnommish\n\nWeapons: daggers, darts, slings, quarterstaff, light crossbow\n\nArmor: -";
                color: Palette.text_color;
                font-size: 16px;
            }
        }
    }
}