import { Heading, Label, SingleStat } from "../text_widgets.slint";
import { VerticalBox } from "std-widgets.slint";
import { Palette } from "../palette.slint";
import { SlintCharacter, SlintStat } from "../../logic.slint";


export component StatsPanel {
    in-out property <SlintCharacter> in-character;
    VerticalLayout {
        min-width: 125px;
        alignment: start;
        spacing: 30px;
        Heading {
            height: 40px;
            width: 125px;
            text: "Stats";
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        for stat[i] in in-character.stats : SingleStat {
            name: stat.name;
            value: stat.value;
            modifier: stat.modifier;
            color: stat.color;
        }
    }
}