import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { TopBar } from "elements/panels/top_bar.slint";
import { Palette } from "elements/palette.slint";
import { StatsPanel } from "elements/panels/stats.slint";
import { Line } from "elements/drawing.slint";
import { SavesProficiencies } from "elements/panels/saves_profs.slint";
import { SlintCharacter } from "logic.slint";
import { EditMode } from "elements/globals.slint";
import { AcHpMoneyPanel } from "elements/panels/ac_hp_money.slint";

import "fonts/typey.otf";

export component AppWindow inherits Window {
    width: 1920px;
    height: 1000px;
    in-out property <SlintCharacter> character;

    default-font-family: "Typey McTypeface";

    // callbacks
    callback add-money(string, string);
    callback subtract-money(string, string);

    callback take-damage(string);
    callback heal(string);
    callback add-temp-hp(string);
    callback subtract-temp-hp(string);

    background: Palette.background_color;
    TopBar {in-character: character;}
    HorizontalLayout {
        x: 0;
        y: 100px;
        alignment: start;

        StatsPanel {in-character: character;}

        Line {
            from: {x: 0, y: 0};
            to: {x: 0, y: 100.0};
            stroke: Palette.text_color;
        }

        SavesProficiencies {in-character: character;}
        
        Line {
            from: {x: 0, y: 0};
            to: {x: 0, y: 100.0};
            stroke: Palette.text_color;
        }

        AcHpMoneyPanel {
            in-character: character;
            add-money(string, int) => {
                add-money(string, int);
            }
            subtract-money(string, int) => {
                subtract-money(string, int);
            }
            take-damage(string) => {
                take-damage(string);
            }
            heal(string) => {
                heal(string);
            }
            add-temp-hp(string) => {
                add-temp-hp(string);
            }
            subtract-temp-hp(string) => {
                subtract-temp-hp(string);
            }
        }

        Line {
            from: {x: 0, y: 0};
            to: {x: 0, y: 100.0};
            stroke: Palette.text_color;
        }
    }
}
