export struct SlintStat {
    name: string,
    short-name: string,
    value: int,
    modifier: string,
    color: color,
    saving-throw-proficiency: bool,
    modifier_with_proficiency: string,
}

export struct SlintSkill {
    name: string,
    proficiency: bool,
    expertise: bool,
    modifier: string,
}

export struct SlintMoney {
    cp: int,
    sp: int,
    ep: int,
    gp: int,
    pp: int,
}

export struct SlintShortSpellEntry {
    name: string,
    level: int,
    school: string,
    casting-time: string,
    range: string,
    components: string,
    duration: string,
    description: string,
    higher-levels: string,
    ritual: bool,
    classes: [string],
    prepared: bool,
}
export struct SlintCharacter {
    name: string,
    level: int,
    class: string,

    exp: int,
    armor-class: int,
    initiative: string,
    speed: int,

    max-hp: int,
    current-hp: int,
    temp-hp: int,

    hit-dice-total: string,
    hit-dice-left: string,

    money: SlintMoney,
    
    death-saves-successes: int,
    death-saves-failures: int,

    proficiency-bonus: string,
    stats: [SlintStat],
    skills: [SlintSkill],

    cantrips: [SlintShortSpellEntry],
    spells1: [SlintShortSpellEntry],
    spells2: [SlintShortSpellEntry],
    spells3: [SlintShortSpellEntry],
    spells4: [SlintShortSpellEntry],
    spells5: [SlintShortSpellEntry],
    spells6: [SlintShortSpellEntry],
    spells7: [SlintShortSpellEntry],
    spells8: [SlintShortSpellEntry],
    spells9: [SlintShortSpellEntry],

    spell-slots: [string],

    features-traits: string,
}

