import { SlintCharacterShortInfo } from "../../logic.slint";
import { CharacterSelectTopBar } from "../panels/character_select_top_bar.slint";
import { CharacterSelectGrid } from "../panels/character_select_grid.slint";
import { Line } from "../drawing.slint";
import { HorizontalBox } from "std-widgets.slint";

export component CharacterSelectState {
    width: 100%;
    height: 100%;

    callback character-selected(string);

    in property <[SlintCharacterShortInfo]> all-characters;

    CharacterSelectTopBar {}

    HorizontalLayout {
        x:0;
        y:100px;
        Rectangle {
            width: 300px;
            height: 100%;
        }

        Line {
            width: 6px;
            height: 100%;
            from: {x:0, y:0};
            to: {x:0, y:1};        
        }

        CharacterSelectGrid {
            width: 1920px - 600px;
            all-characters: all-characters;
            character-selected(name) => {
                character-selected(name);
            }
        }

        Line {
            width: 6px;
            height: 100%;
            from: {x:0, y:0};
            to: {x:0, y:1};        
        }

        Rectangle {
            width: 300px;
            height: 100%;
        }
    }
}